# Generated by Django 3.2.8 on 2021-12-14 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fbv_app', '0002_alter_student_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='score',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
