# Generated by Django 3.2.8 on 2021-10-19 13:44

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('travel_points', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('1', 'Moscow'), ('2', 'New York'), ('3', 'Paris')], default=('1', '2'), max_length=2), size=None)),
            ],
        ),
    ]
