#chown -R $(whoami):$(whoami) core/
#export UID=${UID} && export GID=${GID}
#docker-compose run app sh -c "django-admin startproject app ."


version: "3"

services:
  app:
    user: $UID:$GID
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./core:/core
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"