#chown -R $(whoami):$(whoami) core/
#export UID=${UID} && export GID=${GID}
#docker-compose run app sh -c "django-admin startproject app ."
#docker-compose run app sh -c "python manage.py test"

version: "3"

services:
  app:
    user: $UID:$GID
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./core:/core
    command: >
      sh -c "python manage.py wait_for_db &&
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    environment:
      - SECRET_KEY='supertopsecretkey'
      - DB_HOST=db
      - DB_NAME=recipe_app_db
      - DB_USER=postgres
      - DB_PASS=supersecretpassword
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    environment:
      - POSTGRES_DB=recipe_app_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=supersecretpassword