# Generated by Django 3.2.8 on 2021-11-12 13:09

# python manage.py sqlmigrate emp_app 0001
#
# BEGIN;
# --
# -- Create model Employee
# --
# CREATE TABLE "emp_app_employee" ("id" bigserial NOT NULL PRIMARY KEY, "first_name" varchar(30) NOT NULL, "last_name" varchar(30) NOT NULL, "email" varchar(35) NOT NULL, "salary" double precision NOT NULL);
# COMMIT;

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=35)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
