# Generated by Django 3.2.8 on 2021-11-28 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbv_crud_app', '0002_auto_20211128_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='headman',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='fbv_crud_app.headman'),
        ),
    ]
