# Generated by Django 3.2.8 on 2021-11-28 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbv_crud_app', '0004_alter_student_headman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='headman',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='fbv_crud_app.headman'),
        ),
    ]
