# Generated by Django 3.2.8 on 2021-11-28 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbv_crud_app', '0007_alter_student_headman'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='headman',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='fbv_crud_app.student'),
        ),
        migrations.DeleteModel(
            name='Headman',
        ),
    ]
