# Generated by Django 3.2.8 on 2021-11-28 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fbv_crud_app', '0009_studentcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentcard',
            name='student',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_card', to='fbv_crud_app.student'),
        ),
    ]
