version: '3.9'

services:
  web:
    build: .
    container_name: web
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
    ports:
      - 10555:8000
    volumes:
      - .:/django_docker