# Generated by Django 3.2.8 on 2021-11-28 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fbv_crud_app', '0008_auto_20211128_1045'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('description', models.TextField()),
                ('rating', models.IntegerField()),
                ('students', models.ManyToManyField(related_name='courses', to='fbv_crud_app.Student')),
            ],
        ),
    ]
