GET http://127.0.0.1:8000/api/fbv_authors/
Accept: application/json

###

POST http://127.0.0.1:8000/api/fbv_authors/
Content-Type: application/json

{
  "first_name": "Sashкинс",
  "last_name": "Пушkins",
  "birth_year": 1799
}

###

PUT http://127.0.0.1:8000/api/fbv_authors/7
Content-Type: application/json

{
  "first_name": "Sashкинс",
  "last_name": "Пушkins",
  "birth_year": 1799
}

###

PATCH http://127.0.0.1:8000/api/fbv_authors/7
Content-Type: application/json

{
  "first_name": "Sashкaускас",
  "last_name": "Пушkinsонс",
  "birth_year": 1799
}

###